;; added by Custom
;
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(bmkp-last-as-first-bookmark-file "/Users/tmelhase/.emacs.d/bookmarks")
 '(browse-url-browser-function (quote browse-url-kde))
 '(c-insert-tab-function (quote insert-tab))
 '(c-syntactic-indentation nil)
 '(dired-garbage-files-regexp
   "\\(?:\\.\\(?:aux\\|bak\\|dvi\\|log\\|orig\\|rej\\|toc\\|pyc\\)\\)\\'")
 '(dired-listing-switches "-alh")
 '(git-gutter:modified-sign "|")
 '(global-git-gutter-mode t)
 '(gud-gdb-command-name "gdb --annotate=1")
 '(ido-file-extensions-order (quote (".jade" ".coffee")))
 '(imenu-create-index-p nil)
 '(indent-tabs-mode nil)
 '(ipython-command "/usr/local/bin/ipython")
 '(large-file-warning-threshold nil)
 '(neo-banner-message nil)
 '(neo-mode-line-type (quote none))
 '(neo-theme (quote arrow))
 '(nodejs-repl-command "/Users/tmelhase/src/natural-bin/icoffee-plain")
 '(nxml-child-indent 2)
 '(nxml-outline-child-indent 4)
 '(py-python-command "/usr/local/bin/ipython")
 '(py-shebang-startstring "#!/bin/env python")
 '(py-shell-name "ipython")
 '(py-start-run-py-shell nil)
 '(sgml-basic-offset 4)
 '(show-trailing-whitespace t)
 '(w3m-default-display-inline-images t)
 '(w3m-use-toolbar nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#181818" :foreground "#c8c8c8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "unknown" :family "Droid Sans Mono"))))
 '(ac-completion-face ((t (:foreground "darkorange" :underline t))))
 '(antlr-keyword ((t (:inherit font-lock-keyword-face :foreground "#B09378"))))
 '(antlr-ruledef ((t (:inherit font-lock-function-name-face :foreground "#587EB0"))))
 '(antlr-tokenref ((t (:inherit font-lock-type-face :foreground "#ffc080"))))
 '(bmkp-heading ((t (:inherit font-lock-type-face))))
 '(bmkp-local-directory ((t (:inherit font-lock-function-name-face))))
 '(buffer-menu-buffer ((t (:foreground "#9AC0CD"))))
 '(company-preview ((t (:foreground "darkgray" :underline t))))
 '(company-preview-common ((t (:inherit company-preview))))
 '(company-tooltip ((t (:background "lightgray" :foreground "black"))))
 '(company-tooltip-common ((((type x)) (:inherit company-tooltip :weight bold)) (t (:inherit company-tooltip))))
 '(company-tooltip-common-selection ((((type x)) (:inherit company-tooltip-selection :weight bold)) (t (:inherit company-tooltip-selection))))
 '(company-tooltip-selection ((t (:background "steelblue" :foreground "green"))))
 '(compilation-info ((t (:inherit success))))
 '(compilation-line-number ((t (:inherit font-lock-keyword-face))))
 '(completions-first-difference ((t (:inherit bold :foreground "#FFB90F"))))
 '(cursor ((t (:background "#777"))))
 '(custom-link ((t (:inherit link))))
 '(custom-state ((((class color) (background dark)) (:foreground "#1874cd"))))
 '(diff-added ((t (:inherit diff-changed :background "black" :foreground "#70FB67"))))
 '(diff-hunk-header ((t (:inherit diff-header :background "black" :foreground "#3469D0"))))
 '(diff-removed ((t (:foreground "orange"))))
 '(eshell-prompt ((t (:foreground "#79B579"))))
 '(font-lock-comment-delimiter-face ((default (:foreground "#999999")) (((class color) (min-colors 16)) nil)))
 '(font-lock-comment-face ((((class color) (min-colors 88) (background dark)) (:foreground "#999999"))))
 '(font-lock-constant-face ((t (:foreground "#D8ECF5" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "#BF9AFF"))))
 '(font-lock-keyword-face ((t (:foreground "#7095D7" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#76BEBA"))))
 '(font-lock-type-face ((t (:foreground "#99C8F4"))))
 '(font-lock-variable-name-face ((t (:foreground "#B8B784"))))
 '(git-gutter:added ((t (:foreground "#404040"))))
 '(git-gutter:deleted ((t (:foreground "#400000"))))
 '(git-gutter:modified ((t (:foreground "#404040"))))
 '(git-gutter:separator ((t (:foreground "cyan"))))
 '(ido-subdir ((t (:foreground "#6c71c4"))))
 '(isearch ((((class color) (min-colors 88) (background dark)) (:background "#ff4500" :foreground "#ffffff"))))
 '(lazy-highlight ((((class color) (min-colors 88) (background dark)) (:background "#caff70" :foreground "black"))))
 '(link ((((class color) (min-colors 88) (background dark)) (:foreground "#7AB5DB" :underline t))))
 '(magit-branch ((t (:inherit magit-header :background "#202020" :foreground "#A28ABC"))))
 '(magit-diff-del ((t (:inherit diff-removed))))
 '(magit-item-highlight ((t (:inherit highlight))))
 '(magit-log-sha1 ((t (:foreground "#64A6A5"))))
 '(magit-section-title ((t (:inherit font-lock-comment-face))))
 '(menu ((t (:background "#202020" :foreground "#f0f0f0"))))
 '(minibuffer-prompt ((t (:foreground "#7095D7"))))
 '(mode-line ((t (:foreground "#ffffff" :box (:line-width -1 :color "#303030")))))
 '(mode-line-buffer-id ((t (:foreground "#7095D7"))))
 '(mode-line-emphasis ((t nil)))
 '(mode-line-inactive ((t (:foreground "#505050" :box (:line-width -1 :color "#101010")))))
 '(neo-banner-face ((t (:foreground "orange red" :weight bold))))
 '(popup-face ((t (:inherit menu))))
 '(popup-menu-selection-face ((t (:background "#7095D7" :foreground "white"))))
 '(py-decorators-face ((t (:inherit font-lock-keyword-face :foreground "OrangeRed"))))
 '(region ((((class color) (min-colors 88) (background dark)) (:background "#7AB5DB" :foreground "#191919"))))
 '(scroll-bar ((t (:foreground "red"))))
 '(success ((t (:foreground "#7AB5DB" :weight bold))))
 '(trailing-whitespace ((((class color) (background dark)) (:background "#303030"))))
 '(vertical-border ((t nil))))
