;; added by Custom
;
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(browse-url-browser-function (quote browse-url-kde))
 '(c-insert-tab-function (quote insert-tab))
 '(c-syntactic-indentation nil)
 '(dired-listing-switches "-alh")
 '(git-gutter:modified-sign "|")
 '(global-git-gutter-mode t)
 '(gud-gdb-command-name "gdb --annotate=1")
 '(imenu-create-index-p nil)
 '(indent-tabs-mode nil)
 '(ipython-command "/usr/local/bin/ipython")
 '(large-file-warning-threshold nil)
 '(nodejs-repl-command "/Users/tmelhase/src/natural-bin/icoffee-plain")
 '(nxml-child-indent 2)
 '(nxml-outline-child-indent 4)
 '(py-python-command "/usr/local/bin/ipython")
 '(py-shebang-startstring "#!/bin/env python")
 '(py-shell-name "ipython")
 '(py-start-run-py-shell nil)
 '(sgml-basic-offset 4)
 '(show-trailing-whitespace t)
 '(w3m-default-display-inline-images t)
 '(w3m-use-toolbar nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#131313" :foreground "#cccccc" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 150 :width normal :foundry "apple" :family "Envy Code R"))))
 '(antlr-keyword ((t (:inherit font-lock-keyword-face :foreground "#B09378"))))
 '(antlr-ruledef ((t (:inherit font-lock-function-name-face :foreground "#587EB0"))))
 '(antlr-tokenref ((t (:inherit font-lock-type-face :foreground "#ffc080"))))
 '(buffer-menu-buffer ((t (:foreground "#9AC0CD"))))
 '(compilation-info ((t (:inherit success))))
 '(compilation-line-number ((t (:inherit font-lock-keyword-face))))
 '(completions-first-difference ((t (:inherit bold :foreground "#FFB90F"))))
 '(custom-link ((t (:inherit link))))
 '(custom-state ((((class color) (background dark)) (:foreground "#1874cd"))))
 '(eshell-prompt ((t (:foreground "#79B579"))))
 '(font-lock-comment-delimiter-face ((default (:foreground "#999999")) (((class color) (min-colors 16)) nil)))
 '(font-lock-comment-face ((((class color) (min-colors 88) (background dark)) (:foreground "#999999"))))
 '(font-lock-constant-face ((((class color) (min-colors 88) (background dark)) (:foreground "#FFFFCD" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "#A17BDB"))))
 '(font-lock-keyword-face ((((class color) (min-colors 88) (background dark)) (:foreground "#A28ABC" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#64A683"))))
 '(font-lock-type-face ((((class color) (min-colors 88) (background dark)) (:foreground "#7AB5DB"))))
 '(font-lock-variable-name-face ((t (:foreground "#B8B784"))))
 '(fringe ((t (:background "#151515"))))
 '(git-gutter:added ((t (:foreground "#404040"))))
 '(git-gutter:deleted ((t (:foreground "#400000"))))
 '(git-gutter:modified ((t (:foreground "#404040"))))
 '(git-gutter:separator ((t (:foreground "cyan"))))
 '(ido-subdir ((t (:foreground "#6c71c4"))))
 '(isearch ((((class color) (min-colors 88) (background dark)) (:background "#ff4500" :foreground "#ffffff"))))
 '(lazy-highlight ((((class color) (min-colors 88) (background dark)) (:background "#caff70" :foreground "black"))))
 '(link ((((class color) (min-colors 88) (background dark)) (:foreground "#7AB5DB" :underline t))))
 '(magit-branch ((t (:inherit magit-header :background "#202020" :foreground "#A28ABC"))))
 '(magit-item-highlight ((t (:inherit highlight :foreground "#64A6A5"))))
 '(magit-log-sha1 ((t (:foreground "#64A6A5"))))
 '(magit-section-title ((t (:inherit font-lock-comment-face))))
 '(minibuffer-prompt ((((background dark)) (:foreground "#7AB5DB"))))
 '(mode-line ((t (:background "#131313" :foreground "#ffffff" :box (:line-width -1 :color "#303030")))))
 '(mode-line-buffer-id ((t (:foreground "#7AB5DB"))))
 '(mode-line-emphasis ((t nil)))
 '(mode-line-inactive ((t (:background "#101010" :foreground "#505050" :box (:line-width -1 :color "#101010")))))
 '(py-decorators-face ((t (:inherit font-lock-keyword-face :foreground "OrangeRed"))))
 '(region ((((class color) (min-colors 88) (background dark)) (:background "#7AB5DB" :foreground "#191919"))))
 '(scroll-bar ((t (:foreground "red"))))
 '(success ((t (:foreground "#7AB5DB" :weight bold))))
 '(trailing-whitespace ((((class color) (background dark)) (:background "#303030"))))
 '(vertical-border ((t nil))))
